ribbon:
  #指的是建立连接所用的时间，适用于网络状况正常的情况下,两端连接所用的时间
  ReadTimeout: 5000
  #指的是建立连接后从服务器读取到可用资源所用的时间
  ConnectTimeout: 5000

feign:
  hystrix:
    enabled: true
logging:
  level:
    # feign日志以什么级别监控哪个接口
    com.atguigu.service.PaymentService: debugserver

application:
  user:
    name:  helloWorld
    password:  123456
